### ISSUE TITLE
Add last comment to ticket's body

### ISSUE THREAD

**Issue by DnRuban** [DnRuban/Taskhelper#24]

**Comment by Lebed02** [comment]
All works good

**Comment by Lebed02** [comment]
The channel receives old tickets, probably because of the comments (:)

**Comment by Lebed02** [comment]
All works good

**Comment by Lebed02** [comment]
Because there were a lot of requests from the bot, Telegram timed out, at that moment the bot wanted to resend the ticket, but because of the timeout it couldn't. As a result, the ticket was resent without buttons, but with an added comment, after the action with the ticket it was resent again, the channel now has two identical tickets, only one without buttons

![Image](https://github.com/DnRuban/Taskhelper/assets/103741333/fa5c368c-037a-4e5d-8202-a6b922715b12)

**Comment by Lebed02** [comment]
The bug remains, the ticket is duplicated, a new one is created, and the old one remains and cannot be interacted with in any way

It also happened that by performing the same actions some tickets did not appear in the channel, there was a ticket "#ak #bb", after the comment appeared only in the channel "bb" moved, after clicking on CC the ticket appeared in the channel "ak" too

I also noticed that there can be two comments in a ticket at once (past and new). To reproduce it you need to send one comment many times to a ticket, then immediately send a new comment to the same ticket

**Comment by Lebed02** [comment]
I wrote a comment but it is not displayed, I restarted the bot and clicked on "CC", it didn't help, only when I wrote a comment again the ticket was updated. Maybe it happened because of timeout

![Image](https://github.com/DnRuban/Taskhelper/assets/103741333/488c4789-e132-46af-b2da-9e58c048cd06)

![Image](https://github.com/DnRuban/Taskhelper/assets/103741333/e7d65dad-3e8d-4ebc-bab5-e93009cd9f3f)

**Comment by Lebed02** [comment]
I will finish checking the tasc after the problem with bot freezing is solved

**Comment by Lebed02** [comment]
All works good
